### ISSUE TITLE
রেজিস্ট্রেশন পেইজ সহজীকরণ

### ISSUE THREAD

**Issue by Mohammad04G** [medigeneit/cmeer#3]
রেজিস্ট্রেশন করার জন্য যে পেইজ আছে সেটাতে বর্তমানে ডিটেলস ইনফরমেশন দেওয়া প্রয়োজন হয়।

কিন্তু ইউজারের সুবিধার্থে রেজিস্ট্রেশন প্রসেস সহজ করার জন্য প্রয়োজনীয় ব্যবস্থা গ্রহণ করা দরকার।
আপাতত শুধুমাত্র 
নাম, 
মোবাইল নাম্বার, 
ইমেইল এড্রেস, 
মেডিকেল কলেজ(জেনেসিস এ যে রকম আছে সে রকম , ক্লিক করলে মেডিকেল কলেজের লিস্ট দেখাবে সেখান থেকে তার মেডিকেল কলেজ সিলেক্ট করবে), 
ইউজার আইডি (ব্র্যাকেটে লেখা থাকবে BMDC No/Unique 6 digit No) , 
পাসওয়ার্ড, 
কনফার্ম পাসওয়ার্ড

এরপরে সাবমিট করলে রেজিস্ট্রেশন হয়ে যাবে।
পাসওয়ার্ড রিকভারি অপশন টা যেন একটিভ থাকে।

একাডেমিক ইনফর্মেশন এবং অ্যাড্রেস দেওয়ার যে অপশন গুলো রয়েছে সেগুলো "এডিট প্রোফাইল" ক্লিক করে সম্পন্ন করে নিবে।

অর্থাৎ রেজিস্ট্রেশন করার পরেই সে তার প্রোফাইল ড্যাশবোর্ডে এ চলে যাবে ।

**Comment by saifulislam-saif** [comment]
Completed
